const { TelegramGateway } = require('./lib/gateway');

function firstDefined(...values) {
  for (const value of values) {
    if (value !== undefined && value !== null) return value;
  }
  return undefined;
}

function toBool(value, fallback = false) {
  if (value === undefined || value === null || value === '') return fallback;
  if (typeof value === 'boolean') return value;
  return !['0', 'false', 'no', 'off'].includes(String(value).trim().toLowerCase());
}

function toInt(value, fallback) {
  const n = Number(value);
  return Number.isFinite(n) && n >= 0 ? Math.floor(n) : fallback;
}

function toList(value) {
  if (Array.isArray(value)) return value.map(v => String(v).trim()).filter(Boolean);
  return String(value || '').split(',').map(v => v.trim()).filter(Boolean);
}

function normalizeConfig(host, slot = {}) {
  const legacy = host.channels?.telegram || {};
  const botToken = String(firstDefined(slot.botToken, legacy.botToken, host.telegramBotToken, process.env.TELEGRAM_BOT_TOKEN, '') || '').trim();
  return {
    enabled: toBool(firstDefined(slot.enabled, legacy.enabled), !!botToken),
    botToken,
    dmPolicy: String(firstDefined(slot.dmPolicy, legacy.dmPolicy, 'pairing') || 'pairing'),
    groupPolicy: String(firstDefined(slot.groupPolicy, legacy.groupPolicy, 'open') || 'open'),
    requireMention: toBool(firstDefined(slot.requireMention, legacy.requireMention), true),
    allowFrom: toList(firstDefined(slot.allowFrom, legacy.allowFrom, [])),
    groupAllowFrom: toList(firstDefined(slot.groupAllowFrom, legacy.groupAllowFrom, [])),
    webhookUrl: String(firstDefined(slot.webhookUrl, legacy.webhookUrl, '') || '').trim(),
    webhookSecret: String(firstDefined(slot.webhookSecret, legacy.webhookSecret, '') || '').trim(),
    webhookPath: String(firstDefined(slot.webhookPath, legacy.webhookPath, '/webhooks/telegram') || '/webhooks/telegram').trim(),
    textChunkLimit: toInt(firstDefined(slot.textChunkLimit, legacy.textChunkLimit), 4000),
    chunkMode: String(firstDefined(slot.chunkMode, legacy.chunkMode, 'length') || 'length'),
    sessionMode: String(firstDefined(slot.sessionMode, legacy.sessionMode, 'topic') || 'topic'),
  };
}

function mirrorToHost(host, cfg) {
  host.channels = host.channels || {};
  host.channels.telegram = {
    ...(host.channels.telegram || {}),
    ...cfg,
  };
  host.telegramBotToken = cfg.botToken || null;
  host.plugins = host.plugins || {};
  host.plugins.telegram = { ...(host.plugins.telegram || {}), ...cfg };
}

function telegramPairingTool(api, gateway) {
  const pairing = () => api._appContext?.gateways?.pairing || null;
  const telegramGateway = () => gateway || api._appContext?.gateways?.getGateway?.('telegram') || null;

  return {
    namespaced: false,
    platforms: ['web', 'telegram'],
    mutating: true,
    description: 'Manage Telegram DM pairing requests generated by this Telegram channel plugin. Use this when the owner gives you a Telegram pairing code such as ABCD-2345 and asks to pair, approve, authorize, allow, revoke, or list Telegram access.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: ['list_pending', 'list_approved', 'approve', 'revoke'],
          description: 'Pairing action. Use approve for a pending code, list_pending to inspect outstanding codes, list_approved to inspect approved Telegram user IDs, or revoke to remove an approved user ID.',
        },
        code: {
          type: 'string',
          description: 'Pairing code shown to the Telegram user. Required for action=approve. Hyphen and case are optional.',
        },
        id: {
          type: 'string',
          description: 'Telegram user ID. Required for action=revoke.',
        },
        notify: {
          type: 'boolean',
          description: 'For approve, send a short Telegram DM letting the user know they are paired. Default true.',
        },
        message: {
          type: 'string',
          description: 'Optional custom notification message for action=approve.',
        },
      },
      required: ['action'],
    },
    execute: async (input = {}) => {
      const store = pairing();
      if (!store) return { ok: false, error: 'Telegram pairing store is unavailable.' };

      const action = String(input.action || 'list_pending');
      if (action === 'list_pending') {
        return { ok: true, channel: 'telegram', pending: store.listPending('telegram') };
      }
      if (action === 'list_approved') {
        return { ok: true, channel: 'telegram', approved: store.listApproved('telegram') };
      }
      if (action === 'revoke') {
        const id = String(input.id || '').trim();
        if (!id) return { ok: false, error: 'id is required for revoke.' };
        return { ok: store.revokeApproved('telegram', id), channel: 'telegram', id };
      }
      if (action !== 'approve') {
        return { ok: false, error: `Unknown telegram_pairing action: ${action}` };
      }

      const code = String(input.code || '').trim();
      if (!code) return { ok: false, error: 'code is required for approve.' };

      const result = store.approveCodeForChannel('telegram', code);
      if (!result) return { ok: false, error: 'Code not found or expired.', channel: 'telegram', code };

      const out = { ok: true, ...result };
      if (input.notify !== false) {
        try {
          const gw = telegramGateway();
          const text = input.message || 'Pairing approved. You can message me now.';
          if (gw?.sendMessage) {
            const sent = await gw.sendMessage(result.id, text);
            out.notification = sent?.error ? { ok: false, error: sent.error } : { ok: true };
          } else {
            out.notification = { ok: false, error: 'Telegram gateway cannot send notifications right now.' };
          }
        } catch (e) {
          out.notification = { ok: false, error: e.message };
        }
      }
      return out;
    },
  };
}

async function reconcileGateway(api, gateway, cfg) {
  const manager = api._appContext?.gateways;
  if (!manager?._started || !gateway) return;
  if (cfg.enabled) {
    if (gateway.getStatus?.() !== 'connected') {
      await manager.connectGateway('telegram');
    }
  } else if (gateway.running) {
    await gateway.disconnect();
  }
}

module.exports = function register(api) {
  const host = api.getHostConfig();

  api.registerSettingsPane({
    tab: 'channels',
    title: 'Telegram',
    description: 'Connect a Telegram bot as a channel plugin. Supports DMs, groups, forum topics, polling/webhook mode, recent-message reads, reactions, attachments, and voice notes.',
    schema: [
      { key: 'enabled', label: 'Enable Telegram channel', type: 'toggle', default: false },
      { key: 'botToken', label: 'Bot token', type: 'password', secret: true, envFallback: 'TELEGRAM_BOT_TOKEN',
        help: 'Token from BotFather. Leave blank to keep the stored value.' },
      { key: 'dmPolicy', label: 'DM policy', type: 'select', default: 'pairing',
        options: [
          { value: 'pairing', label: 'Pairing required' },
          { value: 'open', label: 'Allow any DM' },
          { value: 'block', label: 'Block DMs' },
        ] },
      { key: 'groupPolicy', label: 'Group policy', type: 'select', default: 'open',
        options: [
          { value: 'open', label: 'Allow groups' },
          { value: 'allowlist', label: 'Only listed groups' },
          { value: 'block', label: 'Block groups' },
        ] },
      { key: 'requireMention', label: 'Require mention in groups', type: 'toggle', default: true },
      { key: 'allowFrom', label: 'Allowed DM user IDs', type: 'text',
        help: 'Comma-separated Telegram user IDs. Used by pairing/allowlist policies.' },
      { key: 'groupAllowFrom', label: 'Allowed group chat IDs', type: 'text',
        help: 'Comma-separated group chat IDs for allowlist mode.' },
      { key: 'sessionMode', label: 'Session mode', type: 'select', default: 'topic',
        options: [
          { value: 'topic', label: 'Separate forum topics' },
          { value: 'chat', label: 'One session per chat' },
        ] },
      { key: 'textChunkLimit', label: 'Text chunk limit', type: 'number', default: 4000 },
      { key: 'chunkMode', label: 'Chunking mode', type: 'select', default: 'length',
        options: [
          { value: 'length', label: 'Length based' },
          { value: 'paragraph', label: 'Paragraph aware' },
        ] },
      { key: 'webhookUrl', label: 'Webhook URL (optional)', type: 'text',
        help: 'Leave blank to use polling. Set when Telegram should call this instance.' },
      { key: 'webhookPath', label: 'Webhook path', type: 'text', default: '/webhooks/telegram' },
      { key: 'webhookSecret', label: 'Webhook secret', type: 'password', secret: true },
    ],
  });

  mirrorToHost(host, normalizeConfig(host, api.getConfig()));

  const gateway = api.registerChannelGateway(
    'telegram',
    ({ config, log, agent, pairing }) => new TelegramGateway(config, log, agent, pairing),
    { label: 'Telegram', aliases: ['tg'] }
  );

  api.registerTool('telegram_pairing', telegramPairingTool(api, gateway));

  api.onConfigChange(async (newCfg) => {
    const cfg = normalizeConfig(host, { ...api.getConfig(), ...newCfg });
    mirrorToHost(host, cfg);
    await reconcileGateway(api, gateway, cfg);
  });

  api.onShutdown(() => gateway.disconnect?.());
};
