apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "spore.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.manager.serviceKey }}
  MANAGER_SERVICE_KEY: {{ .Values.manager.serviceKey | quote }}
  {{- end }}
  {{- if .Values.manager.credentials.password }}
  MANAGER_PASS: {{ .Values.manager.credentials.password | quote }}
  {{- end }}
  {{- if .Values.agent.discord.token }}
  DISCORD_TOKEN: {{ .Values.agent.discord.token | quote }}
  {{- end }}
  {{- if .Values.agent.telegram.botToken }}
  TELEGRAM_BOT_TOKEN: {{ .Values.agent.telegram.botToken | quote }}
  {{- end }}
  {{- if .Values.agent.web.authPass }}
  SPORE_WEB_AUTH_PASS: {{ .Values.agent.web.authPass | quote }}
  {{- end }}
